# -*- coding: utf-8 -*-
"""word cloud in python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/103lGeaR1pnmZ9raR0azgOpZ3tGll2ntp
"""

pip install wordcloud

pip install matplotlib

# importing the required libraries
import matplotlib.pyplot as plt
from wordcloud import WordCloud, STOPWORDS


#reading the text file
text_file = open("spiderman.txt", "r").read()
wordcloud = WordCloud(height = 1080, width = 1920,colormap = 'jet',background_color = "white", max_words = 500, stopwords = set(STOPWORDS)).generate(text_file)
plt.figure(figsize=(30, 30))
plt.imshow(wordcloud) 
plt.axis("off")

wordcloud.to_file("interstellar.png")

import numpy as np
from PIL import Image

maskArray = np.array(Image.open("902379.png"))
text_file = open("spiderman.txt", "r").read()
wordcloud = WordCloud(height = 1000, width = 1000,background_color = "white",colormap = 'flag', 
                      max_words = 1000, stopwords = set(STOPWORDS),mask=maskArray).generate(text_file)
plt.figure(figsize=(20, 20))
plt.imshow(wordcloud) 
plt.axis("off")

wordcloud.to_file("spiderman_flag.png")

